export const USER_REGISTER = "user/register"
export const USER_LOGIN = "user/login"
export const GET_USER_INFO = "user"

export const NEW_WORKOUT = "/workouts"
export const ALL_USER_WORKOUTS = "/workouts"
export const ALL_WORKOUT_OPTIONS = "/workouts/options"
export const BEST_WORKOUT_EXERCISE = "/workouts/best"

export const FOOD_PRODUCT = "/food"
export const TODAY_FOOD_PRODUCT = "/food/today"
export const FOOD_PRODUCT_HISTORY = "/food/history"

export const NEW_STUDENT = "/trainer/student"
export const ALL_STUDENTS = "/trainer/student"
export const GET_SINGLE_USER = "/trainer/student"
export const NEW_TRAINING_PLAN = "/trainer/plan"
export const ADD_NEW_DIET_PRODUCT = "/trainer/diet"
export const REMOVE_DIET_PRODUCT = "/trainer/diet"
export const GET_STUDENT_DIET = "/trainer/diet"

export const GET_DIET = "/student/diet"
export const GET_TRAINING_PLAN = "/student/plan"
export const GET_TRAINER_REQUEST = "/student/trainerRequest"
export const SEND_STUDENT_TRAINER_DECISION = "/student/trainerRequest"
export const DELETE_TRAINER = "/student/trainer"

export const GET_USERS = "/admin/user"
export const DELETE_USER = "/admin/user"
export const CHANGE_USER_ROLE = "/admin/user/role"
export const CHANGE_USER_PASSWORD = "/admin/user/password"
export const GET_SINGLE_USER_DATA = "/admin/user"
