export const USER_REGISTER = "/register"
export const USER_LOGIN = "/login"
export const NEW_WORKOUT = "/workouts"
export const ALL_USER_WORKOUTS = "/workouts"
export const FOOD_PRODUCT = "/foodProduct"
