export { USER } from "./sliceNames"
export {
    USER_REGISTER,
    USER_LOGIN,
    NEW_WORKOUT,
    ALL_USER_WORKOUTS,
    FOOD_PRODUCT,
    TODAY_FOOD_PRODUCT,
    FOOD_PRODUCT_HISTORY,
    BEST_WORKOUT_EXERCISE,
    NEW_STUDENT,
} from "./apiRoutes"
export {
    INITIAL_REP_COUNT,
    EXERCISE_NAME,
    REPS_QUANTITY,
    SERIES_QUANTITY,
    WEIGHT_QUANTITY,
} from "./workout"
