export { MainLayout } from "./MainLayout/MainLayout"
export { AuthLayout } from "./AuthLayout/AuthLayout"
export { ProfileLayout } from "./ProfileLayout/ProfileLayout"
export { TrainerLayout } from "./TrainerLayout/TrainerLayout"
export { AdminLayout } from "./AdminLayout/AdminLayout"
